### ISSUE TITLE
Potential softlock dying after exiting nonexistent Rosa portal

### ISSUE THREAD

**Issue by jangler** [jangler/oos-randomizer#1]
From dragonc0 – you respawn inside a tree if you exit the Rosa portal from Subrosia, then die before setting another save point.

**Comment by jangler** [comment]
This probably also happens with S+Q.

**Comment by jangler** [comment]
The fix is probably just to remove the bush over the portal.

**Comment by jangler** [comment]
That sort of fix could also be applied to the "shovel gift" softlock by removing one of the snow piles in front of the house. They don't really add anything to the game, and not having to place the shovel early would open up more possibilities.

**Comment by Drenn1** [comment]
I remember hearing that the Link's Awakening randomizer took care of softlocks by implementing a way to warp Link back to the starting house.

For the shovel, the snow piles prevent you from getting the shovel before you obtain winter, so they're not quite pointless.

**Comment by jangler** [comment]
The snow piles are only there in winter; in other seasons the door is just closed.

**Comment by jangler** [comment]
Need to actually activate the portal from the start to avoid the problem of respawning in a tree, but it looks like the tile replacement is just dependent on generic room flag checks. It would be possible to set those flags ($c79a, bits 6 and 7) by overwriting the useless second item interaction for opening the wooden sword chest, but that's very much a hack and I don't like it at all.

**Comment by Drenn1** [comment]
Could you change the room flag check to check for bit 4 (set upon visiting the room, ie. always in this case)?

**Comment by jangler** [comment]
No, because by "generic room flag checks" I mean that `and $40` is run on every room, and that needs to be nonzero in order for for room to be in the desired state.

**Comment by jangler** [comment]
Umm, actually it's `and c` where c is $40 and I'm only seeing it for the Rosa portal room now. I need to check all this again lol

**Comment by jangler** [comment]
Ok, no, I was thinking of `bit 7,a` at 4:5e18, which appears to be called on every screen transition.

**Comment by jangler** [comment]
Took a nap, stopped being dumb, and fixed it from the overworld by changing the tile replacement table instead of the code. Problem is, when you come out of a portal, bit 4 isn't set until after after that check happens, and zero `and` anything is still zero.

**Comment by Drenn1** [comment]
Here's an evil hack for you, assuming it's the same in seasons: if the bitmask is set to $f0, the change applies to all unlinked games. ($f1 applies to linked games, and $f2 applies after being an unlinked game.)

I'm assuming the data you're looking at corresponds to "data/singleTileChanges.s".

**Comment by jangler** [comment]
Yup, looks like it corresponds.

That's wild. I'm doing it.

**Comment by jangler** [comment]
Doesn't work :(
