### ISSUE TITLE
Must not have pirate's bell when first talking to captain

### ISSUE THREAD

**Issue by jangler** [jangler/oos-randomizer#12]
When the player talks to the captain with the bell, the ship sails out of Subrosia / Samasa desert, meaning that the player can no longer talk to the ghost pirate, pick up his skull, or find the item that replaces the rusty bell (AFAIK).

**Comment by Drenn1** [comment]
Could this not have been solved by modifying or removing some flag checks, instead of adding a softlock check in the randomizer?

**Comment by jangler** [comment]
What do you have in mind? The ship/skull remaining in the desert after the pirates depart, or not being able to depart until you get the item in the rusty bell slot?

**Comment by Drenn1** [comment]
The former would be easier. Perhaps we can just skip the part where you need to talk to the ghost skeleton, and make it so that he's always in the top-right corner of the desert. If I recall, in a normal game, he even stays there after the ship leaves.

tbh I always eye those softlock checks skeptically. This one makes it so that the rusty bell can't be obtained without the desert item, right? Seems needlessly limiting.

**Comment by jangler** [comment]
It's definitely limiting. I did consider those options, but I rejected them as being too confusing and illogical. Yes it's a randomizer and it'll do all sorts of wacky things, but I want to minimize the amount that the player has to "learn" the randomizer if they already know the game well.

**Comment by Drenn1** [comment]
Even from a story standpoint, he's a ghost who's in two places at once. To me, it doesn't seem too confusing to make talking to the ghost optional, though it may need a readme note.

Worst-case scenario, either the player talks to the ghost unnecessarily, or they see he's not there and they check the top-right of the desert to see his skull is there. But, it's your call.

**Comment by jangler** [comment]
Don't think I really needed to change the game logic after all, but I did in https://github.com/jangler/oos-randomizer/commit/e79aa55b4820d404f2454bd88f2367760889a3b9.
