### ISSUE TITLE
Make fists an item

### ISSUE THREAD

**Issue by jangler** [jangler/oos-randomizer#14]
Getting treasure $02 allows Link to throw punches as if he's wearing the fist ring. I need to test this a bit more, but I think the main problem will be that there are obviously no graphics, text, or equip screen information associated with the item, which would be confusing at the very least.

**Comment by Drenn1** [comment]
It's possible to give it the "ricky's gloves" sprites at least in the inventory menu (see "treasureDisplayData" in the disassembly), but it looks messed up when equipped. And it would also be easy to confuse with Ricky's Gloves themselves when you get them.

**Comment by Drenn1** [comment]
Yeah, that could work I suppose.
How many rings open up progression in any way? I saw mentions of the first ring, toss ring, and maybe expert's ring?

**Comment by jangler** [comment]
I included fist ring, expert's ring, toss ring, and energy ring, but they seem to always get slotted as extras, so maybe they aren't useful for progression after all.

**Comment by jangler** [comment]
The problem for fist, expert's, and energy rings is that bombs satisfy nearly the same requirements that they do, and bombs are necessarily available from the start, unless the shop items are changed. The problem for toss ring is that it's only potentially useful for one room in d6 and another in d7, and by the time you get there you're likely to have other solutions.

**Comment by jangler** [comment]
Think I'm going to bury this for the time being, for a mixture of philosophical and technical reasons.
