### ISSUE TITLE
Minimum Length Option

### ISSUE THREAD

**Issue by deathaplenty** [jangler/oos-randomizer#27]
An option like -maxlen, but instead, it requires a minimum number of slotted items to be included in the route.

**Comment by jangler** [comment]
I feel like there's a better model to use for the whole goal / forbid / maxlen( / minlen) parameters but just adding a minlen will probably be the solution for 1.3.

**Comment by jangler** [comment]
These options were really niche and more trouble then they were worth IMO. Technically this is a breaking change and would make the next version 2.0 according to semver, but I'm sticking with 1.4 😛
