### ISSUE TITLE
softlock going down the sunken falls cave

### ISSUE THREAD

**Issue by churine** [jangler/oos-randomizer#28]
Diving with the Flippers into the one-way cave in southern sunken city (the one that has the pyramid jewel in a linked game) takes you to the northeast of woods of winter.
without the ability to make it winter to navigate them nor gale seeds to warp, you can't get out of the area the waterfalls take you
![dairando_000](https://user-images.githubusercontent.com/19752470/43738742-fc2c7e1e-99c5-11e8-8a18-eadea6472eaa.png)
![ohno](https://user-images.githubusercontent.com/19752470/43738844-51da0e80-99c6-11e8-9b56-6e188733e6b3.png)

**Comment by jangler** [comment]
I had no idea this place existed. Shows I haven't played the game casually in six years. I'll see whether it makes more sense to add a softlock route check or prevent the one-way somehow.

**Comment by jangler** [comment]
Isn't that effectively the same unless you really want the gasha seed?

But, that might be possible since there does appear to be a warp interaction in the room, just to set your entry point when you fall down, that could be turned into a staircase if the compressed tilemap accommodates it.
