### ISSUE TITLE
Did H&S before losing Cape, can't get it back now

### ISSUE THREAD

**Issue by WashedUpLinkshot** [jangler/oos-randomizer#44]
more in-depth: I used Pegasus + Cape to backdoor to Piratians and wandered into the H&S and did it, headed east and they took my Cape from me, went and did H&S again but only got a Gold Ore.

**Comment by jangler** [comment]
Fixed in [1.5.1](https://github.com/jangler/oos-randomizer/releases/tag/1.5.1); you can `-update` your ROM to get feather/cape back the next time you do hide and seek.
