### ISSUE TITLE
What to do about flutes

### ISSUE THREAD

**Issue by jangler** [jangler/oos-randomizer#52]
Flutes let you do weird, mutually exclusive things with animals, like swim before flippers with Dimitri, jump before feather with Ricky and Moosh, punch bombable walls open with Ricky, remove snow piles before shovel with… all of them? Or just Ricky and Moosh? Currently the randomizer knows you *can* do these things, but only ever "requires" you to get a flute for traversing Spool Swamp and Natzu.

The main problem is that if you buy a flute, you're locking yourself out of an animal companion until you can reach southern Spool Swamp in the right season [(spring is an absolute mess)](https://d1u5p3l4wpay3k.cloudfront.net/zelda_gamepedia_en/6/67/Holodrum_Spring.png). Practically speaking, this is admittedly unlikely to be an issue with the stairway between Eastern Suburbs and Sunken City and the general restrictions on item placement.

What would probably be nicest for logic purposes is if each seed only had one flute, and the Subrosian dance hall, the Horon Village shop, and Ricky all give the same one. Possibly identified from the start.

**Comment by raekuul** [comment]
While Dimitri is my animal companion of choice, there is wisdom in forcing one animal companion for the sake of item logic. (And it would get me to take Ricky as an animal companion for a change)

**Comment by jangler** [comment]
This is tangential, but there's a chance I might look at making Dimitri's flute the second Subrosian dancing prize instead of the sixth. A couple of people suggested / asked about it today and six is a damn stupid number of times to have to do dancing to get Dimitri's flute, considering that Ricky's flute costs 10 rupees and Moosh's costs 150 (easily obtained in vanilla from Hero's Cave + the chests in Horon Village + the old man under the tree in the southeast corner).

**Comment by raekuul** [comment]
If/When you do make fixed flutes, please do change the requirement from six to less-than-six. It's no Goron Dance by any means (much as I'd prefer that), but it's still not exactly the easiest Simon Says in the series.

**Comment by jangler** [comment]
The other possibility would be to make there be only one flute, and randomize it like a normal item. No special Subrosian dance prize, no flute from Ricky if you give him his gloves before you get a flute, and the Horon Village shop item could be randomized like the other single-purchase ones in 1.6.

**Comment by jangler** [comment]
Did the thing I talked about in my last post.
