### ISSUE TITLE
[Disruptive] Tree Warping & Magnet Boulders

### ISSUE THREAD

**Issue by WashedUpLinkshot** [jangler/oos-randomizer#55]
Tree Warping out of a dungeon that has a Magnet Boulder will retain its position and paste it onto the overworld.

**Comment by WashedUpLinkshot** [comment]
...and just to the left of that Magnet Boulder was a Minecart in the middle of the water, that could be jumped into and takes me nowhere!
![Boulder from D7](https://user-images.githubusercontent.com/38393190/44621589-bfaa0c80-a876-11e8-931b-d2878bb6b066.png)
![Boulder from D5](https://user-images.githubusercontent.com/38393190/44621590-c20c6680-a876-11e8-9899-5222ec8503a7.png)
![Minecart from D5](https://user-images.githubusercontent.com/38393190/44621591-c5075700-a876-11e8-8770-eb8f3540fd11.png)

**Comment by jangler** [comment]
I think the solution to this is just going to be not allowing tree warp from indoor locations, since you can always save warp to the entrance and then tree warp from there.

I might also look at what the code for being warped to outside a dungeon after getting the essence does, but if it's anything more than trivial then I'll probably opt for the former. I never intended tree warp to be a "feature" (although I expected it to be used that way anyway), just a mechanism to use if you're softlocked by location.

**Comment by WashedUpLinkshot** [comment]
thinking about this based on #56, and maybe the solution is to eliminate the Tree Warp altogether, instead making S&Q start you at North Horon (like ALttP S&Q to Link's House) if done anywhere in the overworld or caves. this could theoretically be achieved by altering your respawn location the moment the title screen comes up, so that you can still death warp to your last entrance for speed purposes.

**Comment by jangler** [comment]
That's roughly how the first (and never released) implementation of tree warp worked, actually. Selecting S+Q set your save point to <somewhere> and instantly killed you, forcing a deathwarp. Speedrunners use S+C + soft reset anyway, so they don't lose anything if the behavior of S+Q is changed.

I probably could do that; it's just a bunch more code. Disallowing it indoors would just be another 5 bytes.

**Comment by jangler** [comment]
Tree warping limited to outdoor (overworld and Subrosia) areas in https://github.com/jangler/oos-randomizer/commit/0a1b42573a5da91339225f154e60c26247f08f24.

**Comment by Drenn1** [comment]
Just thought I'd point out that these are "static objects" (objects which remember their locations), and indeed the very last thing an essence does before warping you out is call the "clearStaticObjects" function. Shouldn't be difficult to implement that if you were so inclined.
