### ISSUE TITLE
[Logic] X-Shaped Jewel Chest

### ISSUE THREAD

**Issue by WashedUpLinkshot** [jangler/oos-randomizer#57]
[oos-randomizer_log_2018-08-27_132132.txt](https://github.com/jangler/oos-randomizer/files/2325040/oos-randomizer_log_2018-08-27_132132.txt)

Logic assumes X-Shaped Jewel Chest is accessible with only Slingshot + Mystery Seeds, foregoing the necessity to light the lantern in order to access the island.

**Comment by jangler** [comment]
It *is* accessible with only the slingshot and mystery seeds—the speedrun route doesn't even bother equipping ember seeds in the slingshot for that chest, since it's faster just to hit the torch with mystery seeds until you get the 1 in 4 chance of the ember seed effect.
