### ISSUE TITLE
Animal companions not requiring prereqs if their region/flute is chosen?

### ISSUE THREAD

**Issue by jangler** [jangler/oos-randomizer#61]
Needs more testing, but I played part of a seed today where the Naztu region was Natzu River, I didn't find Dimitri's flute, and Dimitri was ready and waiting in Sunken City without me needing to give the kids bombs. This isn't really a problem at all for Dimitri in particular, but it could be a problem for Ricky and Moosh.

**Comment by WashedUpLinkshot** [comment]
Had this problem with Moosh the other day. Bought Strange Flute, found Spring Banana, then visited Moosh for the first time and Moosh was ready and waiting, preventing my Strange Flute from becoming Moosh's Flute. Moosh and Strange Flute were required to enter D5 and progress through the seed.
