### ISSUE TITLE
[1.5.8 Logic] Moblin Cliff Chest Error

### ISSUE THREAD

**Issue by WashedUpLinkshot** [jangler/oos-randomizer#62]
The provided log suggests that Moblin Cliff Chest is accessible with Eastern Suburbs Spring + Lift, not considering that the chest itself requires Long Jump or Magnet.

[oos-randomizer_log_2018-09-08_132309.txt](https://github.com/jangler/oos-randomizer/files/2363606/oos-randomizer_log_2018-09-08_132309.txt)

**Comment by jangler** [comment]
Was fixed in https://github.com/jangler/oos-randomizer/commit/899ddb61b8b9a5134802a5f9bf6752ff90ce8ca3, probably going to be released… tomorrow?
