### ISSUE TITLE
[Logic] Floodgate Key lacks canHitSwitch requirement

### ISSUE THREAD

**Issue by WashedUpLinkshot** [jangler/oos-randomizer#64]
[oosrando_2.0.1_b39adbe0_log.txt](https://github.com/jangler/oos-randomizer/files/2386133/oosrando_2.0.1_b39adbe0_log.txt)

The items provided in the log before the Floodgate Key (including Bombs) can't flip the switch to reveal the item beneath it. I could advance by farming 150 Rupees to buy the Flippers and skip that item, though that's not expected in the logic currently.

**Comment by jangler** [comment]
Hah, I just fixed this bug today… using power bracelet to throw a pot onto the lever in the floodgate keeper's house was in the logic, but it specifically doesn't work there because of whatever tile is above the lever.

**Comment by jangler** [comment]
Fixed in 2.0.2.
