### ISSUE TITLE
[Question] Do Ember Seeds count as 200 Rupees?

### ISSUE THREAD

**Issue by WashedUpLinkshot** [jangler/oos-randomizer#66]
Been wondering this since the changelog says it now counts Rupees available before making you purchase anything at the shop, but it only mentions Rupees placed in chests. However, Ember Seeds in any fashion (Sling or Satchel) allow you to get the two 100-rupee secrets in Horon and North Horon without any extra requirements (aside from a way to farm more seeds if you use them poorly).

tl;dr Ember Seeds open up 200 Rupees which purchases all 3 Shop items (Bombs, Shield, Unique)

**Comment by jangler** [comment]
Yes, but the changelog doesn't say anything about rupee counting being restricted to chests. Old men who give rupees are counted if you can reach them, old men who take rupees are counted *against* your total if you can reach them, and the rupee rooms in D2 and D6 are counted as well.
