### ISSUE TITLE
Moosh Cutscene Lock

### ISSUE THREAD

**Issue by isaacbunsen** [jangler/oos-randomizer#68]
Invisible Moosh's banana cutscene locks you in an endless cutscene after dialogue.
Seed f65556ee

**Comment by jangler** [comment]
I'm going to need more information than that.

**Comment by isaacbunsen** [comment]
Game was running fine. No dungeons completed.
Ive included the save file so you can see for yourself.
[oos-randomizer_bugged-moosh.zip](https://github.com/jangler/oos-randomizer/files/2399275/oos-randomizer_bugged-moosh.zip)
Head left twice then up, left and up, where the cutscene will trigger and then never resolve.
I had no flute yet in this save, so I suspect that was related.
I'm not sure what other info I can give.

**Comment by jangler** [comment]
That event even existing in the game (given the randomized flutes) was a bug, so it's gone completely now.
