### ISSUE TITLE
Script command "spawn item on link" replacement / alternative

### ISSUE THREAD

**Issue by jangler** [jangler/oos-randomizer#69]
Currently most scripts that directly give Link items do so using script command $de, which spawns an item interaction directly on Link, causing him to pick it up immediately. This has the limitation that if the item's collection mode is something like "dive", "fall from ceiling", or "chest", it won't work properly, so only unique items can be used.

Custom function $3f21 (used for giving items from shops, etc.) *should* do everything that spawning an item on Link does (gives the item, plays the sound, shows the text), so it might be possible to replace the script command with a call to $3f21 instead. If that doesn't work across the board, maybe a new script command that uses the function could be added and used where applicable.

**Comment by Jigglysaint** [comment]
I'm new here, but I have extensive Oracle of Seasons knowledge(it's been a while so I'm rather rusty)  My notes tell me that at offset FEC2B, or thereabouts is the item attribute data.  Not sure if this has already been edited with the randomizer, but it does control aspects like which items come from chests or fall from the ceiling.  I only started playing the randomizer today, so I don't know the extent of what has been changed.  I'm pretty impressed so far.

**Comment by jangler** [comment]
The item attribute data has been modified from the start; the problem is that an item like 30 rupees has four randomized instances in the game but only one entry in the treasure table.

**Comment by Jigglysaint** [comment]
What are the instances?  BTW the Gasha seed prizes are at 2897C.  I forget if there's a 30 rupee prize in there.  It's possible the different instances of the prize are coded differently, depending on how it is called.  Don't forget there is a lot of script data that is coded using ASM rather than the scripting language.  Again, not sure if this information is something you already have, but the start of all the game's sprites and objects start at 3B60.  The destination of those pointers is interesting, with 3B36 doing a bunch of compares and loading the bank number based on where in the list the pointers fall.  That's the great thing about this game.  Once you understand how the game works, even coding stuff using ASM is easy. This game even has bankswapping on the fly(so no need to do PRG bank bouncing nearly as much).

**Comment by Jigglysaint** [comment]
I also have listed in my list of bookmarks offset 55129 as being the "chest assembler"  I think this is where the different items and their states are defined, but it has been a while since I played with them.  In fact, if you have any questions about anything, I might be able to help.

**Comment by jangler** [comment]
Yeah, the shops in particular have been annoying to work with since they do practically everything through asm (though they're not the only item slots that work that way). I don't think I knew about the sprite/object pointer table in bank 0, just the item sprite data in bank $3f (because of adding entries for items that are normally only sold in shops, etc.), and dynamically loading that data for randomized items in certain locations.

Also not sure if I know anything about the "chest assembler".

The 30 rupee instances are the chest in hero's cave, the chest in dungeon 3, and the chest in the cave in woods of winter, so I guess I miscounted. :stuck_out_tongue:

**Comment by jangler** [comment]
Also, thanks; it's nice to have someone else with a lot of technical game knowledge around. FWIW though, I'm not planning to do any new features with the randomizer for a while… just going to slowly go through the logic for Ages for a while (ugh).

**Comment by Jigglysaint** [comment]
Ah that explains the issue.  The chest in the woods is one of the jewel chests, which means its data is a script.  As for ages, well the good news is most of the data is still the same, so it shouldn't be as hard to figure out.

**Comment by jangler** [comment]
No, the chest in cave you bomb open, not the one you can dive to from sunken city. The one you dive to just has a gasha seed in it, and it's actually an asm function and not a script (same with the jewel chests in eyeglass lake and spool swamp). I'm not really worried about special chests for this issue, since chests are sort of the lowest common denominator for item slots, or about asm functions, since those mostly already use the "give item" function instead of "spawn item" commands—I mean for this issue to specifically address scripts that directly give items (subrosian dance hall, season towers, holly's house, blaino, and master diver).

And yeah, I'm not worried about the data in Ages—mainly just about figuring out exactly what "sequence breaks" you can do in the overworld using time travel, and making sure the logic for more complicated dungeons like Jabu-Jabu is correct.

**Comment by jangler** [comment]
Closing this since I'm using an alternate solution.
