### ISSUE TITLE
Digging up multiple swords gives you the upgrade

### ISSUE THREAD

**Issue by WashedUpLinkshot** [jangler/oos-randomizer#71]
a vanilla bug in Subrosia Sands lets you dig up multiple Star Ores, but with progressives, this actually upgrades the item you'll dig up.

curiously, Noble Sword does not upgrade to Master Sword.

**Comment by jangler** [comment]
What's the vanilla bug? How do I reproduce it?

**Comment by WashedUpLinkshot** [comment]
if you continue to dig in the first Star Ore spot, you'll eventually dig up a duplicate of the item

**Comment by jangler** [comment]
Fixed in 2.1.1.
