### ISSUE TITLE
2.1.4 Change: Poe Sisters don't need that much for their torches

### ISSUE THREAD

**Issue by WashedUpLinkshot** [jangler/oos-randomizer#76]
It is easily possible to light all 4 torches just by walking around and using the Slingshot to light them. I would say it's as easy as jumping over a long pit without the intended requirements, though maybe it takes a little longer to retry the torches if you don't do it in time. I can't remember the last time I failed Satch-less 2nd Torches but I do still mess up D8 Autumnless occasionally, for comparison, which I believe is in the logic?

so, to be specific, D7 2nd Poe requirements should be:

General D7 Access
Wizzrobe Disposal Method (bottom right chest only)
Bombs (blast wall chest and bottom right chest)
Slingshot
Fool's Ore, Sword, Bombs, or Ember Seeds (1st Poe Defeated)
Power Bracelet
Feather (2nd Poe, Isolated Lobby Chest)

that's it, because the Ember Seeds are guaranteed drops from the regrowing bushes (both 1st Poe and 2nd Poe) whether you've harvested some from a tree or not. am I right, or missing something?

(on a tangent, from there I believe it's Flippers to access the next tier of the dungeon, and then a various combination of Magnets, Scent/Mystery Seeds, Cape, and Satchel to open up Cape Chest, Maze Chest, Boss Key, and Boss. Pegasus Seeds are also guaranteed drops from the pots in the middle of the room below Armos Roulette, so you don't need access to that tree, right?)

**Comment by jangler** [comment]
dragonc0 told me that this was possible, so I put it in logic, then tried it, couldn't do it, and took it out again. I could be wrong, but my main concern about putting this in logic is that I think most people won't know it's even possible.

**Comment by WashedUpLinkshot** [comment]
I think the key to doing it is starting with the top left torch and making sure you start at the very bottom edge of it, so you have time to go around and hit the bottom edge of the top right. the torches will be fully lit for a brief moment and that's good enough to wake up the Poe.

as for worrying somebody won't know it's possible, then I think D8 without Autumn should not be in the logic because to the untrained eye, that zig-zaggy gap does not look like something that can be cleared without Moosh.

however what I really believe in is "if it can be done with perseverence, than it shall be done", and if people see something that looks impossible, it encourages them to come here and speak up and learn more.

**Comment by jangler** [comment]
Autumnless D8 kind of got grandfathered in because it's in the speedrun and doesn't require much practice, but I would agree that it's the single most questionable trick in logic.

There has been some general contention lately about what should and should not be in logic, with different parties pulling in different directions. Ultimately there will need to be a "developer-intended" set of logic and an "anything safe and RTA-possible" set, where "safety" is defined in terms of potential to softlock.

**Comment by jangler** [comment]
Addressed in e02976be86f22a902c35c557520c222eba7a14b0. It's not in normal difficulty but it is in hard difficulty.
