### ISSUE TITLE
Don't use L-1 items as filler that can only be reached with L-2 items

### ISSUE THREAD

**Issue by jangler** [jangler/oos-randomizer#8]
As in, don't place a feather in a slot that you can only reach using the cape, even if all the necessary items have been slotted and the rest of the slots just need to be filled with something or other. The four empty magic ring sub IDs might be useful for this.

**Comment by jangler** [comment]
Filling unused slots with insignificant items will probably reduce the problem of long runtime due to filling extra slots with items that could trigger softlock checks.

**Comment by Drenn1** [comment]
Idea: Change it so that all upgradable items will increment the item's level, similar to the satchel, so that the first time you get the "feather/cape", it will always be the feather. The main problem I see with this is that I don't think you can set the text/graphics to adjust itself based on what level you're on already.

**Comment by jangler** [comment]
Yeah, that's an option. I doubt most people will even notice the text, but the graphics are definitely more trouble than they're worth.

It's not hard to prevent this from happening since it's identical in form to the softlock checks I have already (make sure you can't get to x without y), so basically the only concern is runtime if I take that solution.

**Comment by Drenn1** [comment]
Rather than the difficulty of preventing this from happening, I'm thinking more about how to make the randomizer more flexible. Those softlock checks do reduce the possible variety of the randomizer.

**Comment by Drenn1** [comment]
It's not equivalent, in that there are cases where the player could choose one of two chests which both contain the same item at different levels.

**Comment by jangler** [comment]
True!

**Comment by jangler** [comment]
https://github.com/jangler/oos-randomizer/commit/552c327c1f599aaa94970c5044b92b187564be39 doesn't *completely* address this problem, but it's good enough for me.
